# This is a basic workflow to help you get started with Actions

name: CI

env:
  PYTHON_VERSION  : "3.6"
  APP_DIR         : "./api"
  TEST_DIR        : "./api"
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repo
      - uses: actions/checkout@v2

      # Install Python
      - name: install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements-dev.txt
        working-directory: ${{ env.APP_DIR }}

      - name: Lint with flake8
        run: |
          flake8 .
        working-directory: ${{ env.APP_DIR }}

      - name: Test with pytest
        run: |
          pytest
        working-directory: ${{ env.APP_DIR }}
