name: test_build_api

env:
  APP_DIR         : "./api"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.10"]

    steps:
      # Checks-out repo
      - uses: actions/checkout@v2

      # Install Python
      - name: install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
          
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements-dev.txt
        working-directory: ${{ env.APP_DIR }}

      - name: Lint with flake8
        run: |
          flake8 .
        working-directory: ${{ env.APP_DIR }}

      - name: Test with pytest
        run: |
          pytest
        working-directory: ${{ env.APP_DIR }}
