name: CI

env:
  APP_DIR         : "./api"
  TEST_DIR        : "./api"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version'     
        required: true
        default: '3.6'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repo
      - uses: actions/checkout@v2

      # Install Python
      - name: install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ github.event.inputs.python_version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements-dev.txt
        working-directory: ${{ env.APP_DIR }}

      - name: Lint with flake8
        run: |
          flake8 .
        working-directory: ${{ env.APP_DIR }}

      - name: Test with pytest
        run: |
          pytest
        working-directory: ${{ env.APP_DIR }}
